server {
    listen 80;
    server_name jobs.yourcodereview.com 68.183.220.246;
    return 301 https://$host$request_uri;  # Redirect HTTP to HTTPS
}

server {
    listen 443 ssl;
    server_name jobs.yourcodereview.com;

    ssl_certificate /etc/nginx/cert.pem;
    ssl_certificate_key /etc/nginx/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;


    location /add {
            allow 41.66.123.156;
            allow 178.115.44.218;
            allow 178.71.67.95;
            allow 46.53.244.202;
            allow 46.53.187.48;
            allow 149.3.12.152;
	    allow 5.227.30.179;
	    allow 5.227.29.174;
            deny all;

        try_files $uri /index.html;
        root   /usr/share/nginx/html;
        index  index.html index.html;
    }

    location / {
        try_files $uri /index.html;
        root   /usr/share/nginx/html;
        index  index.html index.html;
    }

        location /api {
            proxy_pass https://backend:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
        }


    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

}
