FROM python:3.11-slim

WORKDIR /app
COPY . /app


RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get clean && apt-get update

RUN apt-get -y install locales

RUN echo "LC_ALL=ru_RU.UTF-8" >> /etc/environment
RUN echo "ru_RU.UTF-8 UTF-8" >> /etc/locale.gen
RUN echo "LANG=ru_RU.UTF-8" > /etc/locale.conf
RUN locale-gen ru_RU.UTF-8

RUN apt-get -y install cron

COPY ./parsing/cron-parse /etc/cron.d/parsejobs

RUN chmod 0644 /etc/cron.d/parsejobs

RUN touch /var/log/cron.log

ENV PYTHONPATH=/app

CMD cron && tail -f /var/log/cron.log
