<template>
    <div>
      <router-link
        v-for="job in jobList"
        :key="job.hh_id"
        :to="{ name: 'Vacancy', params: { id: job.hh_id } }"
      >
        <ui-card :item="job" />
      </router-link>
    </div>
  </template>

<script setup>
import UiCard from "@/components/ui/uiCard.vue";

const jobList  = [
    {
        hh_id: "85740036",
        name: "Junior PHP разработчик",
        area: "Минск",
        salary_from: 800,
        salary_to: null,
        salary_currency: "USD",
        employment: "Полная занятость",
        employer: "Спортдата",
    },
    {
        hh_id: "86329523",
        name: "Junior PHP Developer",
        area: "Санкт-Петербург",
        salary_from: null,
        salary_to: null,
        salary_currency: null,
        employment: "Полная занятость",
        employer: "Северная, Птицефабрика",
        professional_roles: "Программист, разработчик",
    },
    {
        hh_id: "86113214",
        name: "Junior Full Stack Web PHP разработчик",
        area: "Санкт-Петербург",
        salary_from: 50000,
        salary_to: null,
        salary_currency: "RUR",
        employment: "Полная занятость",
        employer: "Монолит Северо-Запад",
        professional_roles: "Программист, разработчик",
    },
    {
        hh_id: "86122121",
        name: "Junior Full Stack Programmer Internship (PHP/JS/Mysql)",
        area: "Минск",
        salary_from: null,
        salary_to: null,
        salary_currency: null,
        employment: "Стажировка",
        employer: "Амариллис Солюшенс",
        professional_roles: "Программист, разработчик",
    },
    {
        hh_id: "86221406",
        name: "Junior PHP разработчик",
        area: "Екатеринбург",
        salary_from: null,
        salary_to: null,
        salary_currency: null,
        employment: "Полная занятость",
        employer: "Банклаб",
        professional_roles: "Программист, разработчик",
    },
    {
        hh_id: "85063854",
        name: "Junior Разработчик (PHP, JS)",
        area: "Иркутск",
        salary_from: 40000,
        salary_to: 75000,
        salary_currency: "RUR",
        employment: "Полная занятость",
        employer: "Байкал-Интеграция",
        professional_roles: "Программист, разработчик",
    },
    {
        hh_id: "85321143",
        name: "Junior Backend разработчик (PHP, Laravel)",
        area: "Нижний Новгород",
        salary_from: null,
        salary_to: 48000,
        salary_currency: "RUR",
        employment: "Частичная занятость",
        employer: "makeROI",
        professional_roles: "Программист, разработчик",
    },
    {
        hh_id: "85689075",
        name: "PHP Junior backend разработчик / программист",
        area: "Краснодар",
        salary_from: 30000,
        salary_to: 100000,
        salary_currency: "RUR",
        employment: "Полная занятость",
        employer: "Агентство ИнТОП",
        professional_roles: "Программист, разработчик",
    },
    {
        hh_id: "85286807",
        name: "Junior php developer",
        area: "Москва",
        salary_from: 50000,
        salary_to: 60000,
        salary_currency: "RUR",
        employment: "Полная занятость",
        employer: "Экспресс-Лаундри",
        professional_roles: "Программист, разработчик",
    },
    {
        hh_id: "86256748",
        name: "PHP-разработчик (Junior)",
        area: "Новосибирск",
        salary_from: null,
        salary_to: null,
        salary_currency: null,
        employment: "Полная занятость",
        employer: "Сибирские Сети",
        professional_roles: "Программист, разработчик",
    },
    {
        hh_id: "86221585",
        name: "Программист PHP (Junior)",
        area: "Москва",
        salary_from: 60000,
        salary_to: null,
        salary_currency: "RUR",
        employment: "Полная занятость",
        employer: "Интертрейд",
        professional_roles: "Программист, разработчик",
    },
    {
        hh_id: "85895418",
        name: "PHP, Wordpress разработчик (Junior)",
        area: "Симферополь",
        salary_from: 30000,
        salary_to: null,
        salary_currency: "RUR",
        employment: "Полная занятость",
        employer: "Сайрус",
        professional_roles: "Программист, разработчик",
    },
    {
        hh_id: "85963754",
        name: "Junior PHP developer",
        area: "Казань",
        salary_from: 40000,
        salary_to: 70000,
        salary_currency: "RUR",
        employment: "Полная занятость",
        employer: "Enot.io",
        professional_roles: "Программист, разработчик",
    },
    {
        hh_id: "85829291",
        name: "Junior PHP программист",
        area: "Баку",
        salary_from: 150000,
        salary_to: null,
        salary_currency: "RUR",
        employment: "Полная занятость",
        employer: "Школа рекрутеров IT and Digital",
        professional_roles: "Программист, разработчик",
    },
    {
        hh_id: "86175012",
        name: "Junior Backend Developer (PHP, Symfony)",
        area: "Москва",
        salary_from: null,
        salary_to: null,
        salary_currency: null,
        employment: "Полная занятость",
        employer: "СберЗдоровье",
        professional_roles: "Программист, разработчик",
    },
];
</script>
