
vacancy_list = [
  {
      "id": 1,
      "title": "Младший Python Разработчик",
      "company_name": "ТехКорп",
      "salary": "50,000 USD",
      "location": "Нью-Йорк, США",
      "speciality": "backend",
      "internship": False,
      "remote": True,
      "url": "https://techcorp.com/jobs/1",
      "description": "Ищем младшего Python разработчика для работы в нашей команде."
  },
  {
      "id": 2,
      "title": "Стажёр Data Scientist",
      "company_name": "ДатГен",
      "salary": "Стипендия стажировки",
      "location": "Сан-Франциско, США",
      "speciality": "data science",
      "internship": True,
      "remote": False,
      "url": "https://datagen.com/jobs/2",
      "description": "Стажировка для начинающих Data Scientist."
  },
  {
      "id": 3,
      "title": "Frontend Разработчик",
      "company_name": "ВебВоркс",
      "salary": "60,000 USD",
      "location": "Удалённо",
      "speciality": "frontend",
      "internship": False,
      "remote": True,
      "url": "https://webworks.com/jobs/3",
      "description": "Присоединяйтесь к нашей команде в качестве Frontend разработчика для работы над интересными проектами."
  },
  {
      "id": 4,
      "title": "UX/UI Дизайнер",
      "company_name": "ДизайнХаб",
      "salary": "70,000 USD",
      "location": "Лос-Анджелес, США",
      "speciality": "design",
      "internship": False,
      "remote": False,
      "url": "https://designhub.com/jobs/4",
      "description": "Ищем талантливого UX/UI дизайнера для улучшения наших продуктов."
  },
  {
      "id": 5,
      "title": "DevOps Инженер",
      "company_name": "СистемСолюшнс",
      "salary": "80,000 USD",
      "location": "Берлин, Германия",
      "speciality": "devops",
      "internship": False,
      "remote": False,
      "url": "https://systemsolutions.com/jobs/5",
      "description": "Нам требуется DevOps инженер для поддержки и оптимизации нашей инфраструктуры."
  },
  {
      "id": 6,
      "title": "Аналитик Данных",
      "company_name": "АналитикПро",
      "salary": "55,000 USD",
      "location": "Москва, Россия",
      "speciality": "data analysis",
      "internship": False,
      "remote": False,
      "url": "https://analytikpro.com/jobs/6",
      "description": "Ищем аналитика данных для работы с большими объёмами информации."
  },
  {
      "id": 7,
      "title": "Системный Администратор",
      "company_name": "ИнфоТех",
      "salary": "45,000 USD",
      "location": "Киев, Украина",
      "speciality": "sysadmin",
      "internship": False,
      "remote": False,
      "url": "https://infotech.com/jobs/7",
      "description": "Требуется системный администратор для поддержки корпоративной сети."
  },
  {
      "id": 8,
      "title": "Младший Разработчик Java",
      "company_name": "КодИнк",
      "salary": "50,000 USD",
      "location": "Санкт-Петербург, Россия",
      "speciality": "backend",
      "internship": False,
      "remote": False,
      "url": "https://codeink.com/jobs/8",
      "description": "Ищем младшего Java разработчика для участия в наших проектах."
  },
  {
      "id": 9,
      "title": "Стажёр Тестировщик",
      "company_name": "ТестСофт",
      "salary": "Стипендия стажировки",
      "location": "Минск, Беларусь",
      "speciality": "qa",
      "internship": True,
      "remote": False,
      "url": "https://testsoft.com/jobs/9",
      "description": "Предлагаем стажировку для начинающих тестировщиков ПО."
  },
  {
      "id": 10,
      "title": "Менеджер по Продукту",
      "company_name": "ПродактМенеджмент",
      "salary": "70,000 USD",
      "location": "Алматы, Казахстан",
      "speciality": "product management",
      "internship": False,
      "remote": False,
      "url": "https://productmanagement.com/jobs/10",
      "description": "Требуется менеджер по продукту для работы над новыми проектами."
  },
  {
      "id": 11,
      "title": "Старший Разработчик Ruby",
      "company_name": "РубиПро",
      "salary": "85,000 USD",
      "location": "Прага, Чехия",
      "speciality": "backend",
      "internship": False,
      "remote": False,
      "url": "https://rubypro.com/jobs/11",
      "description": "Ищем старшего разработчика на Ruby для работы над крупными проектами."
  },
  {
      "id": 12,
      "title": "Администратор Баз Данных",
      "company_name": "Датабаза",
      "salary": "60,000 USD",
      "location": "Вильнюс, Литва",
      "speciality": "database",
      "internship": False,
      "remote": False,
      "url": "https://database.com/jobs/12",
      "description": "Требуется администратор баз данных для работы с SQL и NoSQL системами."
  },
  {
      "id": 13,
      "title": "Мобильный Разработчик",
      "company_name": "МобилАпп",
      "salary": "75,000 USD",
      "location": "Бишкек, Кыргызстан",
      "speciality": "mobile development",
      "internship": False,
      "remote": True,
      "url": "https://mobilapp.com/jobs/13",
      "description": "Ищем мобильного разработчика для создания приложений под iOS и Android."
  },
  {
      "id": 14,
      "title": "Инженер по Безопасности",
      "company_name": "СекьюрИТ",
      "salary": "90,000 USD",
      "location": "Таллинн, Эстония",
      "speciality": "security",
      "internship": False,
      "remote": False,
      "url": "https://securit.com/jobs/14",
      "description": "Требуется инженер по безопасности для защиты корпоративных систем."
  },
  {
      "id": 15,
      "title": "Разработчик C++",
      "company_name": "СиПлюсПлюс",
      "salary": "80,000 USD",
      "location": "Рига, Латвия",
      "speciality": "backend",
      "internship": False,
      "remote": False,
      "url": "https://cplusplus.com/jobs/15",
      "description": "Ищем разработчика C++ для участия в разработке высокопроизводительных приложений."
  },
  {
      "id": 16,
      "title": "Старший Разработчик JavaScript",
      "company_name": "ДжаваСкриптПро",
      "salary": "85,000 USD",
      "location": "София, Болгария",
      "speciality": "frontend",
      "internship": False,
      "remote": True,
      "url": "https://javascriptpro.com/jobs/16",
      "description": "Требуется старший разработчик JavaScript для работы над веб-приложениями."
  },
  {
      "id": 17,
      "title": "Системный Архитектор",
      "company_name": "АрхитекТех",
      "salary": "100,000 USD",
      "location": "Хельсинки, Финляндия",
      "speciality": "architecture",
      "internship": False,
      "remote": False,
      "url": "https://architekttech.com/jobs/17",
      "description": "Ищем системного архитектора для проектирования и оптимизации корпоративных систем."
  },
  {
      "id": 18,
      "title": "Инженер Программного Обеспечения",
      "company_name": "СофтИнженер",
      "salary": "75,000 USD",
      "location": "Белград, Сербия",
      "speciality": "software engineering",
      "internship": False,
      "remote": True,
      "url": "https://softengineer.com/jobs/18",
      "description": "Ищем инженера программного обеспечения для разработки и поддержки наших продуктов."
  },
  {
      "id": 19,
      "title": "Разработчик Go",
      "company_name": "ГоПро",
      "salary": "80,000 USD",
      "location": "Тбилиси, Грузия",
      "speciality": "backend",
      "internship": False,
      "remote": True,
      "url": "https://gopro.com/jobs/19",
      "description": "Требуется разработчик Go для создания высоконагруженных сервисов."
  },
  {
      "id": 20,
      "title": "Инженер по Автоматизации Тестирования",
      "company_name": "ТестАвто",
      "salary": "70,000 USD",
      "location": "Ереван, Армения",
      "speciality": "ml",
      "internship": False,
      "remote": False,
      "url": "https://testauto.com/jobs/20",
      "description": "Ищем инженера по автоматизации тестирования для разработки автотестов."
  }
]