"""add autoincrement

Revision ID: 319b6a2db3f5
Revises: 3b97f7c6bea4
Create Date: 2024-03-11 19:09:24.782846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319b6a2db3f5'
down_revision: Union[str, None] = '3b97f7c6bea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
