"""add autoincrement

Revision ID: 3b97f7c6bea4
Revises: 1ad2c479816d
Create Date: 2024-03-11 19:05:36.169512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b97f7c6bea4'
down_revision: Union[str, None] = '1ad2c479816d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancies_copy')
    op.alter_column('vacancies', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_vacancies_company_name'), 'vacancies', ['company_name'], unique=False)
    op.create_index(op.f('ix_vacancies_external_id'), 'vacancies', ['external_id'], unique=False)
    op.create_index(op.f('ix_vacancies_id'), 'vacancies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancies_id'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_external_id'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_company_name'), table_name='vacancies')
    op.alter_column('vacancies', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_table('vacancies_copy',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('speciality', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('internship', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('remote', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_publication', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
