"""Initial migration

Revision ID: ed8b6279e603
Revises: 
Create Date: 2024-01-15 18:08:12.739393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed8b6279e603'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vacancies_company_name', table_name='vacancies')
    op.drop_index('ix_vacancies_external_id', table_name='vacancies')
    op.drop_index('ix_vacancies_id', table_name='vacancies')
    op.drop_table('vacancies')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('speciality', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('internship', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('remote', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vacancies_pkey')
    )
    op.create_index('ix_vacancies_id', 'vacancies', ['id'], unique=False)
    op.create_index('ix_vacancies_external_id', 'vacancies', ['external_id'], unique=False)
    op.create_index('ix_vacancies_company_name', 'vacancies', ['company_name'], unique=False)
    # ### end Alembic commands ###
